language: php

php:
  - 7.2

services:
  - mysql
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - vendor
    - node_modules

before_install:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install -y cf-cli

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod

before_script:
  - mysql -e 'create database cwk_testing;'
  - php artisan migrate --force --seed

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: script
  script: bash deploy.sh
  on:
    repo: RoyalBoroughKingston/cwk-api
    branch: develop
