language: php

php:
  - 7.2

services:
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: deb https://packages.cloudfoundry.org/debian stable main
        key_url: https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key
    packages:
      - mysql-server
      - cf-cli

dist: trusty

sudo: required

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - node_modules

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run dev

before_script:
  - mysql -e 'create database ck_testing;'
  - php artisan migrate --force --seed
  - php artisan passport:keys

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    repo: RoyalBoroughKingston/ck-api
    branch: develop

notifications:
  slack:
    rooms:
      - secure: "PHlrXjgJ8BUGiDVPjKs4plzRYvSoW1BxnhPFrIGbFZLEngN6aBdkg3W5ev0YGQ4kUL5tNx/d2WuSnkwNBs/82SVb9Tnsq/R7mt2n+woYPpGmi0olXprir/VqQ5OmryCelJGxXv+IWJ8NMaovtJzmvLQxNJnglKvlHEibyhZCQ8LJhTHxQEsZ80KHVRb8+HTfeEm9vqCneYM6BwQwk7rZx2Dqi2HCFhSSb3lg94XkCQrS1H9ObY7pUvI4omDwSIhSwjaAWlDVXnJKbD1PtleaejOSbSeqiY82o1GzcoGrLL8wJ1fyAtGvlkjcQN+SlAzHyPE/7cJM816nvoABFJToQBgsZLjoLz5skaWWt8Fh2fkix6oK0v5xHWs6J5LQa9AgwUsmS7wjXc61x+5ydxH4QtFprvbQNBnqdCCJnXDQjkDGdfJrDI8nqV+uOvwVtQ/pSfXJF6wtcnJIO1mJhhpOg/A2fghe2eXoTN1Oh/LGhQAjJ6slTmXc8e4MIRGJ7WX0eHd8ZM1vHNyfZmTVXkysOdGdRQQcnmtji+qW6jF3F9Sa2kTYd9El9Og4DYdcvCS+1CGO1zbNRx5I/yKH2Fhcld0a6hFQpVXty1H86dEGvt0fS0CAqhk4lSNG2ZSPBRYfm7RWfgqWJuFmkJjErrb2NtebNN0ESvWvl3GY2ZUgrh0="
    on_success: always
