os: linux
dist: xenial

if: tag IS blank
branches:
  only:
    - master
    - develop

language: python
python:
  - "2.7"

services:
  - docker

env:
  - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin

before_install:
  - gcloud -q components update

before_script:
  - sudo service mysql stop
  - ./develop build
  - ./develop up -d
  - ./develop composer install
  - ./develop run --rm -T app mv .env.example .env
  - ./develop artisan key:generate
  - ./develop artisan passport:keys

script:
  - ./develop composer test:style
  - ./develop composer test:unit

after_failure:
  - cat storage/logs/testing.log

deploy:
  - provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
      branch:
        - master
        - develop
