language: php

php:
  - 7.2

services:
  - mysql
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - vendor
    - node_modules

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e 'create database cwk_testing;'
  - php artisan migrate --force --seed

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: cloudfoundry
  api: api.cloud.service.gov.uk
  username: matt@ayup.agency
  password:
    secure: PcRRc8z8ZX4uny991GnYe0fimlVYaL573Mp//PZsIB5maOkGvZzQNaEnqjTnVXzDuwS/eUKWrl8IjrgVsfevWc/FyccD9xqpxlySeii4xO5I9xYnWyjLN50+dSVJjVAC86ZEzoHuhE0V+rMMIiTH8ziXrFcmT+OqUWLZESVS/ZpWJBZS0GLMImdM1It+vLrEPytX1uvSxqoKUZVB4iZs+aap0p1a6POteCCBKNWLkWD9kxIjrM5x3exlWHa/ec3RNBkAM9S6OsIyO/16d5i9cI47NR++WhpoVI1kVGRrska7NSn/5vAemxfC5NZ7kG/eVVUdCble0NOJJtoTB0q2cf8YT5iUh5uNUbiB5wfctjG4WSAjn0SKEXhmo6bHW5mZknV+kC2px5JHwI4kh/RMHPkfq7rlpy3oItqiTKWtUgAbdcEi0jnH5UmwbGOSTNhYwTI4H0o81pHNIr+IVD/YwiIMAvvPUc7UWmd1cJdQJ8yfyak+55EhVmL+1XrnLpGgpwLNNVk4Q5qJCFhothGmGRxhDMEMdyRnEldpbFS+qNPPgLtKs0TMAGnbUWnV8cucml18ey6yoXxJXv1Pwg5LJmAYBpWqxp+0mU57hds+p/YcMBRuGWJoD9hyfeVvd/I119Jv/yvTwXm59BfTU02VMZxR/s9kUUzKrLgpMUlqSBo=
  organization: kingston-council-digital-design
  space: connectwellkingston-dev
  on:
    repo: RoyalBoroughKingston/cwk-api
    branch: develop
