os: linux
dist: xenial

branches:
  only:
    # Tagged releases
    - /^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$/
    # Master
    - master
    # Develop
    - develop

language: python

python:
  - "3.6"

services:
  - docker

before_script:
  - if [ ! -z "$DOCKER_USER" ] && [ ! -z "$DOCKER_PWD" ];  then echo ${DOCKER_PWD} | docker login --username ${DOCKER_USER} --password-stdin; fi
  - sudo service mysql stop
  - ./develop build
  - ./develop up -d
  - ./develop npm ci
  - ./develop npm run dev
  - ./develop composer install
  - ./develop run --rm -T app mv .env.example .env
  - ./develop artisan key:generate
  - ./develop artisan passport:keys

script:
  - ./develop composer test:style
  - ./develop composer test:unit

after_failure:
  - cat storage/logs/testing.log

before_deploy: |
  if ! [[ ${HAS_RAN_BEFORE_DEPLOY} ]]; then
    export HAS_RAN_BEFORE_DEPLOY="TRUE"

    echo "Compiling assets for production..."
    ./develop npm run prod

    echo "Installing AWS CLI..."
    rm -Rf ${PWD}/aws
    wget -q -O awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    unzip awscliv2.zip
    ${PWD}/aws/install
    aws --version

    echo "Installing CloudFoundry CLI..."
    apt-get update && apt-get install -y --allow-unauthenticated gnupg
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    sudo apt-get update && sudo apt-get install -y --allow-unauthenticated cf7-cli
  fi

deploy:
  # Tagged releases
  - provider: script
    script: ENVIRONMENT=production CF_API=https://api.cloud.service.gov.uk CF_ORGANISATION=$CF_ORGANISATION CF_SPACE=$CF_SPACE_PRODUCTION CF_USERNAME=$CF_DEPLOY_USERNAME CF_PASSWORD=$CF_DEPLOY_PASSWORD CF_INSTANCES=$CF_INSTANCES_PRODUCTION CF_ROUTE=$CF_ROUTE_PRODUCTION bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$
  # Develop
  - provider: script
    script: ENVIRONMENT=staging CF_API=https://api.cloud.service.gov.uk CF_ORGANISATION=$CF_ORGANISATION CF_SPACE=$CF_SPACE_STAGING CF_USERNAME=$CF_DEPLOY_USERNAME CF_PASSWORD=$CF_DEPLOY_PASSWORD CF_INSTANCES=$CF_INSTANCES_STAGING CF_ROUTE=$CF_ROUTE_STAGING bash .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
