language: php

php:
  - 7.2

services:
  - mysql
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - vendor
    - node_modules

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e 'create database cwk_testing;'
  - php artisan migrate --force --seed

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: cloudfoundry
  api: api.cloud.service.gov.uk
  username: matt@ayup.agency
  password:
    secure: "idXsrW+OWYgT8uCHXVXj56d+Nn7FGufK5iAl/yKKzDRymLAX6TiCmbvuwer2/NXc/G7exMwEKYtJGAoyg5kGmHstLVuoSpeM1MEGYqrsmpT3prfhNSRUwMA0gZo1hwlK4NvCKltpn1MJPvokUZNAV3SDS63nA25GJ3Z4QY838dlcRUkgQD+SaNH5emvv4X8/kJTZtpApfSasiZuruMspwKnHRdC6y7sW1NeJR5BcE+zteFV7UapEm76l86KoJqlwCvHquk8FcehSNMPVbwVhU3a+Q2p9L/lppIY//lDSKt2dGmRxVyaMAdM1FXO+ceQOfy0nSi4bunfzu4SFb4I4xvDCzZfvk3VTpwLTbbFIaHDouW0y/Q4+8BIrlZH6IFrKndcF6Ee3+YlzYRJ+TWJCt/J14PBr7KZUDrbvWyERxo1xhlHtsSuB35yjEYNnvrOIOElnHqGYVsMhw1tiHKUA4sZgDndlo+zBpH1Oqsh2C/JpXAd+60HV3jjFLD7mKICvWSb3kWjkoyWp1FPTAEtmmsV7SB14XFM2Xzr0skGOwsGHUpWC5EGb7AR4SfMQImxdCfDZcoK/ESAAwofjO8l44uxv5/ZKrzxGtUPyuncIQTxsVm58J2zQrThVQmPEuO8R3MidfApeVZ9tpTUti5eDpH+axOgG+wTVB61ACA570Zk="
  organization: kingston-council-digital-design
  space: connectwellkingston-dev
  on:
    repo: RoyalBoroughKingston/cwk-api
    branch: develop
