language: php

php:
  - 7.2

services:
  - mysql
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - vendor
    - node_modules

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e 'create database cwk_testing;'
  - php artisan migrate --force --seed

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: cloudfoundry
  api: api.cloud.service.gov.uk
  username: matt@ayup.agency
  password:
    secure: "mqGmuoLYradC0lQfV5bRCD25SoyT1PU0OjtLJ473Wi+3LoYxYNlMVTGDyjcIecxXecZtakqweYnnj/ow2Sgl9M3854aPXf4hOrUNW9lLzTTO6IfX7smJ2f7bdIyaosCPiHvTWLv5ujks1CgqdZj/FwLtywrRrjXEnRr7xTC3FKEbYn38QhTjajC9W6VBJVXmkSlVJ446Cd/F7jUZwrH/93hIzOqkgozWGM+nr3T5j7H2tP1Mj3Rp5iKzQqHwvphzcne1m71505uBZNo826rESLFfOyhUUG7jPqwhntVCgvSpNkq1KcjmTS+67Kg3GEn3Wpi56a3ta26ZlOwzC1PYUeA2iLGydo5TXN/lLhFyRe30Rmei2EQeN3uAwwFULU2PQv3vF4e3tQN0sAUTUZaM8eCZnXq38fDT+Z8xfYIpqtWXa3Rk2FmWjUo20HmGyavwOJsw6z9jFeKPLG6Qd6SQUiDbxYaLrL4zhM8icXUxUv3J3oNb0C7/AkzrvZujPTFMnkoc+O+BjP/7WDyROKIbfcstnAnyYM/WL6iDfi8VFQcFX3qEhBiBBMWZi8TuWBj7swINwWTev1klqsNd9s5giYBjKiV/VJNQMwIOxqRVu9YW2vm3ZTGZjGJhHq+/+HJtZr1FphhcyoQGMDJ6Huk7bNXBIYuNn4sqb7/en6m1ZuQ="
  organization: kingston-council-digital-design
  space: connectwellkingston-dev
  on:
    repo: RoyalBoroughKingston/cwk-api
    branch: develop
