language: php

php:
  - 7.2

services:
  - mysql
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - vendor
    - node_modules

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e 'create database cwk_testing;'
  - php artisan migrate --force --seed

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: cloudfoundry
  api: api.cloud.service.gov.uk
  username: matt@ayup.agency
  password:
    secure: cG0Hj7xAsC/ma7+JS3529DDWKfU/s/V/L5WdhnKu3KcWlYvn5kxFR7tJnzfzGUkZOHadPr2T1bWvXUYuIfEsqz+SXzK2gCkpAEHskX/M1ynGTh+ojk5LZAGkHAvOvQCyytHgsNC1z+mqn/ryM/+z4RJIvNi+vhiVqT2e74gNcVs3SuscKXM4/rzX9+X2dhKABZBDP+9vpwXmthWh98mDKi/n4En9StoKuUHu2Grp1hh+MUKHhX8FVja3ZSG0SVQKkIJKrYujYGy7PMtN69c45/6DT7kmsxLn9owuhlsI8m2AvEq/rPnMkfNF7jct/Skk/nm1z9UfUIT2tdX+mspOpnTz7RFeMkRbMwznaiaD3Xa0cDWv2+8ehzrXcDt5p/ZhH/Vf/DNG2F5f6c9MrIcQe8okX55T54Yj8E7cw/lzUeli3CEDg7BLsg4y/lNTxO5ILDt/y0s6/nyVmdv0vjqgZs+gtD9PejOZCFYiwN8B2NE6Z2twu1EaB1I9oFkoeXqwZrqEOZI4Fy+5MiXuwAYOerNcFZZaRkl+VSB+DWz3lmxN7X8ay4Imd1Dd6A9LSixuMvMI0kUZpoL7kF+/WtUQLwpYczrT8VfiV+epa+8NzGrMC65iUSWjoi1ifjmkt42nQJT3J6wjMxHEnNJZicFc1Uj1RG6PCx9XdaVDWtDj5cg=
  organization: kingston-council-digital-design
  space: connectwellkingston-dev
  on:
    repo: RoyalBoroughKingston/cwk-api
    branch: develop
