openapi: 3.0.1

info:
  title: {{ config('app.name') }} Core API Specification
  description: For using the Core {{ config('app.name') }} API
  version: v1
  contact:
    name: Ayup Digital
    url: https://ayup.agency

servers:
- url: {{ url('/core/v1') }}

paths:
  /locations:
    $ref: /docs/core/paths/locations.yaml#/root
  /locations/{location}:
    $ref: /docs/core/paths/locations.yaml#/nested

  /organisations:
    $ref: /docs/core/paths/organisations.yaml#/root
  /organisations/{organisation}:
    $ref: /docs/core/paths/organisations.yaml#/nested

  /referrals:
    $ref: /docs/core/paths/referrals.yaml#/root
  /referrals/{referral}:
    $ref: /docs/core/paths/referrals.yaml#/nested
  /services/{service}/referrals:
    $ref: /docs/core/paths/referrals.yaml#/services

  /report-schedules:
    $ref: /docs/core/paths/report-schedules.yaml#/root
  /report-schedules/{report_schedule}:
    $ref: /docs/core/paths/report-schedules.yaml#/nested

  /reports:
    $ref: /docs/core/paths/reports.yaml#/root
  /reports/{report}:
    $ref: /docs/core/paths/reports.yaml#/nested
  /reports/{report}/download:
    $ref: /docs/core/paths/reports.yaml#/download

  /search:
    $ref: /docs/core/paths/search.yaml#/root

  /services:
    $ref: /docs/core/paths/services.yaml#/root
  /services/{service}:
    $ref: /docs/core/paths/services.yaml#/nested

  /users:
    $ref: /docs/core/paths/users.yaml#/root
  /users/{user}:
    $ref: /docs/core/paths/users.yaml#/nested

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: {{ url('/oauth/token') }}

security:
  - OAuth2: []

tags:
  - name: Locations
  - name: Organisations
  - name: Referrals
  - name: Report Schedules
  - name: Reports
  - name: Search
  - name: Services
  - name: Users

externalDocs:
  description: GitHub Wiki
  url: https://github.com/RoyalBoroughKingston/cwk-api/wiki
