name: Deploy to Kingston Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Kingston Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run deploy script
        run: .travis/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
          TRAVIS_COMMIT: ${{ github.sha }}
          ENVIRONMENT: production
          ENV_SECRET_ID: ${{ secrets.ENV_SECRET_ID }}
          REPO_URI: ${{ vars.REPO_URI }}
          CLUSTER: ${{ vars.CLUSTER }}
